name: bluufeed_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^1.1.2
  animated_flip_counter: ^0.2.0
  button3d: ^0.1.1
  cloud_firestore: ^4.5.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_messaging: ^14.4.1
  firebase_ui_firestore: ^1.3.0
  flutter_button: ^0.0.4
  flutter_native_text_input: ^2.4.0
  flutter_styled_toast: ^2.1.3
  flutter_svg: ^2.0.5
  flutter_switch: ^0.3.2
  go_router: ^6.5.8
  google_sign_in: ^6.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  modal_bottom_sheet: ^3.0.0-pre
  provider: ^6.0.5
  skeleton_animation: ^0.1.4
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter_icons: # flutter pub run flutter_launcher_icons:main
  min_sdk_android: 21
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  color: "#FFFFFF"
  image_path: "assets/app/ic_launcher.png"

flutter_native_splash: # flutter pub run flutter_native_splash:create
  color: "#FFFFFF"
  color_dark: "#1F222A"
  icon_background_color: "#FFFFFF"
  image: "assets/app/ic_splash.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/app/
    - assets/icon/
    - assets/image/

  fonts:
    - family: nunito
      fonts:
        - asset: assets/font/nunito.ttf
