name: bluufeed_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^6.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter_icons: # flutter pub run flutter_launcher_icons:main
  min_sdk_android: 21
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  color: "#FFFFFF"
  image_path: "assets/app/ic_launcher.png"

flutter_native_splash: # flutter pub run flutter_native_splash:create
  color: "#FFFFFF"
  icon_background_color: "#FFFFFF"
  image: "assets/app/ic_splash.png"
  android: true
  ios: true

  assets:
    - assets/app/
    - assets/font/
    - assets/icon/
    - assets/image/

flutter:
  uses-material-design: true

  # fonts:
  #   - family: ElementalSansPro
  #     fonts:
  #       - asset: assets/fonts/ElementalSansPro.ttf
