name: universe_history_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # animation
  animated_flip_counter: ^0.2.5
  loading_animation_widget: ^1.2.0+3
  page_transition: ^2.0.9

  # core
  device_info_plus: ^4.0.0
  go_router: ^4.3.0
  http: ^0.13.5
  no_context_navigation: ^2.1.2
  path_provider: ^2.0.11
  provider: ^6.0.3

  # firebase
  cloud_firestore: ^3.4.6
  firebase_auth: ^3.4.2
  firebase_core: ^1.21.1

  # layout
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.1.6
  flutter_styled_toast: ^2.1.3
  flutter_svg: ^1.0.3
  modal_bottom_sheet: ^2.1.0
  skeleton_animation: ^0.1.4

  # native
  cupertino_icons: ^1.0.2

  # notification
  firebase_messaging: ^13.0.0
  flutter_local_notifications: ^9.9.0

  # safety
  algolia: ^1.1.1
  expandable_text: ^2.3.0
  flutter_switch: ^0.3.2
  flutterfire_ui: ^0.4.3+7
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: "assets/images/ic_splash.png"
  color: "#ffffff"
  android: true
  ios: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  adaptive_icon_background: "#7291d5"
  image_path: "assets/images/ic_app.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true

flutter:
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: nunito
      fonts:
        - asset: assets/fonts/nunito.ttf
  uses-material-design: true
